/**
 * @fileoverview Configuration for the Prisma CLI.
 * 
 * Relations:
 * - Consumes: `dotenv` for env variables.
 * - Used by: Prisma CLI commands (e.g., `npx prisma db push`).
 * 
 * Logic:
 * - Specifies the schema location, migrations path, and the database connection URL for CLI operations.
 */
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
