/**
 * @file index.ts
 * @description Global TypeScript type declarations and interface definitions.
 * Defines the data contracts for users, auth states, blogs, services, testimonials, and API responses.
 */

// ─── Auth Data Contracts ───────────────────────────────────────────────────

/**
 * Represents a registered user returned by Backendless.
 */
export interface User {
  /** The unique object identifier generated by Backendless database */
  objectId: string;
  /** Primary user email address */
  email: string;
  /** Optional real name of the user */
  name?: string;
  /** Custom user role, acting as an enum */
  role?: 'admin' | 'user';
  /** Session token for authenticating subsequent HTTP transactions */
  'user-token'?: string;
}

/**
 * Interface detailing the Zustand authentication store state and actions.
 */
export interface AuthState {
  /** Current active user details, or null if unauthenticated */
  user: User | null;
  /** Boolean indicating if active async checks (like session restore) are pending */
  isLoading: boolean;
  /** Flag showing user state */
  isAuthenticated: boolean;
  /** Asynchronous login action */
  login: (email: string, password: string) => Promise<void>;
  /** Asynchronous signup action */
  register: (email: string, password: string, name: string) => Promise<void>;
  /** Asynchronous session invalidation action */
  logout: () => Promise<void>;
  /** Asynchronous initial session recovery action */
  restoreSession: () => Promise<void>;
}

// ─── Blog Data Contracts ───────────────────────────────────────────────────

/**
 * Represents a blog post entry retrieved from Backendless.
 */
export interface Blog {
  /** The unique object ID */
  objectId: string;
  /** Post heading/title */
  title: string;
  /** Full article body content (supports paragraph markdown style text) */
  content: string;
  /** Shorter descriptive teaser paragraph */
  excerpt: string;
  /** Explicit author designation */
  authorName: string;
  /** Comma-separated tag list (e.g. "finance,dev,docs") */
  tags?: string;
  /** Visibility status */
  published: boolean;
  /** Flags post for display on featured lists (e.g. Hero cards) */
  featured?: boolean;
  /** Link to post banner image */
  thumbnail?: string;
  /** Timestamp when the entry was stored */
  created: number;
}

// ─── Service Data Contracts ────────────────────────────────────────────────

/**
 * Represents a product or service offering.
 */
export interface Service {
  /** Unique object identifier */
  objectId: string;
  /** Product name */
  title: string;
  /** Core offering descriptions */
  description: string;
  /** Optional price point indicator */
  price?: string;
  /** Lucide-react icon identifier key name */
  icon?: string;
  /** Flags service for highlight in primary home grids */
  featured?: boolean;
  /** Associated client feedback quotation */
  testimonialQuote?: string;
  /** Client name who provided the quote */
  testimonialAuthor?: string;
  /** Image asset illustration link */
  thumbnail?: string;
}

// ─── Testimonial Data Contracts ───────────────────────────────────────────

/**
 * Represents customer feedback quotes.
 */
export interface Testimonial {
  /** Unique identifier */
  objectId: string;
  /** Feedback quotation body */
  quote: string;
  /** Client source author name */
  authorName: string;
  /** Client position role (e.g. "CTO") */
  authorRole: string;
  /** Client company association (e.g. "Stripe") */
  authorCompany?: string;
  /** Avatar profile photo url */
  authorPhoto?: string;
}

// ─── randomuser.me API Contracts ──────────────────────────────────────────

/**
 * Represents a dynamic team member record fetched from randomuser.me.
 */
export interface TeamMember {
  /** Unique credential node housing database UUID */
  login: { uuid: string };
  /** Split name fields */
  name: { first: string; last: string };
  /** Image urls at varying dimensions */
  picture: { large: string; medium: string };
  /** Email address */
  email: string;
  /** Geolocation address information */
  location: { city: string; country: string };
}

/**
 * Structure of the payload returned by randomuser.me query endpoints.
 */
export interface RandomUserResponse {
  /** List of fetched results */
  results: TeamMember[];
}

