/**
 * types.ts — All shared TypeScript type definitions.
 * Central type source for the entire app.
 */

/** Theme flag: true = dark mode, false = light mode */
export type ThemeType = boolean;

// Union type: FilterType can ONLY be one of these 3 strings (nothing else)
export type FilterType = "all" | "active" | "completed";

/**
 * Sort strategy.
 * "manual" enables drag-and-drop; all others disable it.
 */
export type SortType = "manual" | "date_desc" | "date_asc" | "alpha_asc" | "alpha_desc";

/**
 * Single task entity — this is the shape of every todo item.
 * Each field stores one piece of information about the task.
 */
export type Todo = {
  id: string;           // Unique identifier — generated by crypto.randomUUID()
  text: string;         // The task text the user typed in
  completed: boolean;   // true = done (checked off), false = still active
  created_at: number;   // Unix timestamp (Date.now()) for date-based sorting
  manual_index: number; // Position number (0, 1, 2...) for drag-and-drop ordering
};

// Shorthand: TodoArray is just an array of Todo objects
export type TodoArray = Todo[];

/** Reason for rendering EmptyState component */
export type EmptyStateReason = "empty" | "no-results";

/** Sort dropdown option shape (used to render each button in the dropdown) */
export type SortOption = {
  value: SortType;  // The sort value to set when clicked
  label: string;    // The text displayed to the user
};

export type FilterOption = {
  value: FilterType;
  label: string;
};

// interface is like type but designed for object shapes with named properties
// Used here because React components receive props as objects
export interface HeaderProps {
  isDarkMode: boolean; // Passed from App to show the correct theme icon
}

// ── Auth Types ─────────────────────────────────────────
/**
 * A regular user who logged in with name + email.
 * The `type` field is a literal "user" — used to distinguish from GuestUser.
 */
interface RegularUser {
  type: "user";
  name: string;
  email: string;
}

/**
 * A guest user — no credentials, just browsing.
 * The `type` field is a literal "guest" — used to distinguish from RegularUser.
 */
interface GuestUser {
  type: "guest";
}

/**
 * Discriminated union: User is either a RegularUser or a GuestUser.
 * Use `user.type` to narrow which shape you're working with.
 */
export type User = RegularUser | GuestUser;

/**
 * Shape of the auth Zustand store.
 * This describes WHAT data the store holds + WHAT actions it can do.
 */
export type AuthStore = {
  // ── State (data) ──────────────────────────
  user: User | null;   // null = nobody is logged in, User = someone is logged in
  isLoggedIn: boolean; // true = someone is logged in (derived from user !== null)

  // ── Actions (functions) ───────────────────
  login: (name: string, email: string) => void;  // save regular user data (type: "user")
  loginAsGuest: () => void;                       // save guest user data (type: "guest")
  logout: () => void;                             // clear user data (set user back to null)
};
