services:
  # The PostgreSQL Database Service
  postgres:
    image: postgres:latest
    container_name: blogapp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Jakarta48!
      POSTGRES_DB: blogapp
    ports:
      - "5434:5432"
    volumes:
      - pg_blog_data:/var/lib/postgresql
    restart: unless-stopped

  # The Redis Cache Service
  redis:
    image: redis:alpine
    container_name: blogapp_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # The Blog Application Service (Frontend + Backend)
  app:
    image: blog-app:version-1.3
    container_name: my-blog-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Backend API Port
      - "8000:5173"  # Frontend Proxy Port
    env_file:
      - server/.env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

# Define the named volume for database persistence
volumes:
  pg_blog_data:
    name: pg_blog_data
    external: true # Use the volume we already created manually
